POST http://127.0.0.1:8080/v1/login 
Content-Type: application/json;charset=UTF-8 

{
    "username": "admin",
    "password": "Password$$$123s"
}
### failed test
POST http://127.0.0.1:8080/v1/login 
Content-Type: application/json;charset=UTF-8 

{
    "username": "admin",
    "password": "Password23s"
}
  